image: publysher/hugo

before_script:
  - mkdir themes
  - cd themes
  - git clone https://github.com/jbub/ghostwriter

pages:
  script:
    - hugo -t=ghostwriter -d public/

  artifacts:
    paths:
      - public
  only:
    - master
