image: matrixise/hugo-for-wirtel.be

before_script:
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | ssh-add -
  - mkdir -p ~/.ssh
  - echo "${SSH_HOST_KEY}" > "${HOME}/.ssh/known_hosts"
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  - git submodule
  - git submodule update --init

pages:
  script:
    - hugo -t=ghostwriter -d public/
    - rsync -hrvz --chown=www-data:www-data --delete --exclude=_ -e 'ssh -i id_rsa' public/ root@wirtel.be:/home/www/www.wirtel.be/src/
  only:
    - master
