---
newContentEditor: /usr/bin/nvim
theme: original-ghostwriter
title: Stéphane's Blog
baseurl: https://wirtel.be/
copyright: Stéphane Wirtel
googleAnalytics: UA-22059464-1

Author:
  email: stephane@wirtel.be
  name: Stéphane Wirtel
  title: Senior Python Expert
  phone: +32 474 76 80 72
Company:
  email: stephane.wirtel@mgx.io
  site: https://mgx.io/
Params:
  dateFormat: Mon, Jan 2, 2006
  description: About programming, karate, contributions and stuff I enjoy...
  intro: true
  headline: 今日は
  opengraph: true
  shareLinkedIn: true
  shareTwitter: true
  twitterUsername: matrixise
  github: https://github.com/matrixise
  twitter: https://twitter.com/matrixise
  email: stephane@wirtel.be
  linkedin: https://www.linkedin.com/in/stephanewirtel/
  readingTime: true
  readingTimeText: "Estimated reading time:"
Permalinks:
  post: /post/:year/:month/:day/:slug
Privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
    anonymizeIP: true
    respectDoNotTrack: true
    useSessionStorage: false
Taxonomies:
  categories: categories
  series: series
  tags: tags
menu:
  main:
    - name: Posts
      url: /
      weight: 1
    - name: Projects
      url: /project
      weight: 2
    - name: Talks
      url: /talk
      weight: 3
    - name: About
      url: /page/about/
      weight: 5

markup:
  highlight:
    style: solarized-light
