baseurl = "https://wirtel.be/"
#languageCode = "en-us"
title = "Blog"
theme = "ghostwriter"
# pygmentsStyle = "dracula"
# pygmentsUseClasses = true
# pygmentsstyle = "murphy"
# pygmentsstyle = "borland"
#disableRSS=false
#disableKinds=["RSS"]
copyright = "Stéphane Wirtel"
googleAnalytics = "UA-22059464-1"


#uglyUrls = true
#defaultContentLanguage = "en"
#defaultContentLanguageInSubdir = true

#[Languages]
#[Languages.en]
#weight = 1
#name = "English"
#[Languages.fr]
#weight = 2
#name = "Francais"

[Privacy]
[Privacy.disqus]
disable = true

[Privacy.googleAnalytics]
anonymizeIP = true
respectDoNotTrack = true
useSessionStorage = false

[Taxonomies]
tags = "tags"
categories = "categories"
series = "series"

[Permalinks]
post = "/post/:year/:month/:day/:filename"
cv = "/:filename/"

[Author]
name = "Stéphane Wirtel"
email = "stephane@wirtel.be"

[Params]
description = "Description"
intro = false
github = "https://github.com/matrixise"
twitter = "https://twitter.com/matrixise"
opengraph = true
headline = "nothing"
shareTwitter = true
shareLinkedIn = true
dateFormat = "Mon, Jan 2, 2006"

[[menu.main]]
name = "Blog"
url = "/"
weight = 1

[[menu.main]]
name = "Projects"
url = "/project"
weight = 2

[[menu.main]]
name = "Talks"
url = "/talk"
weight = 3

#[[menu.main]]
#name = "Curriculum Vitae"
#url = "/page/cv"
#weight = 6


# [[menu.main]]
#name = "Contact"
#url = "/page/contact/"
#weight = 4

[[menu.main]]
name = "About"
url = "/page/about/"
weight = 5
