# https://taskfile.dev

version: "3"

vars:
  VIRTUALENV: $HOME/.virtualenvs/www.wirtel.be
  LOCAL_PYTHON: "{{ .VIRTUALENV }}/bin/python"
  DOCKER_DEFAULT_PLATFORM: "linux/amd64"

tasks:
  init:
    cmds:
      - echo {{ .LOCAL_PYTHON }}
      - python -m venv {{ .VIRTUALENV }} --upgrade-deps

  dep:compile:
    desc: Compile the dependencies
    cmds:
      - "{{ .LOCAL_PYTHON }} -m uv pip compile --quiet -o scripts/requirements.txt scripts/requirements.in"

  dep:upgrade:
    desc: Upgrade and compile the dependencies
    cmds:
      - "{{ .LOCAL_PYTHON }} -m uv pip compile --upgrade --quiet -o scripts/requirements.txt scripts/requirements.in"

  dep:bootstrap:
    desc: Install the bootstrap tools
    cmds:
      - "{{ .LOCAL_PYTHON }} -m pip install --upgrade uv pip"

  dep:install:
    desc: Install the dependencies
    cmds:
      - "{{ .LOCAL_PYTHON }} -m uv pip install -r scripts/requirements.txt"

  dep:outdated:
    desc: Outdated dependencies
    cmds:
      - "{{ .LOCAL_PYTHON }} -m pip list -o"

  local:cv:generate-tex:
    desc: Generate the CV .tex file from templates and data
    cmds:
      - "{{ .LOCAL_PYTHON }} scripts/generate-cv.py templates/TemplateCV.tex StephaneWirtel.tex"

  local:cv:build-pdf:
    desc: Compile the .tex file to PDF using pdflatex
    cmds:
      - pdflatex -interaction=nonstopmode StephaneWirtel.tex
      - pdflatex -interaction=nonstopmode StephaneWirtel.tex

  local:cv:rebuild:
    desc: Rebuild the CV from scratch (generate .tex + compile PDF)
    cmds:
      - task: local:cv:generate-tex
      - task: local:cv:build-pdf

  refresh:all:
    desc: Refresh all the installations from Scratch
    cmds:
      - rm -rf {{ .VIRTUALENV }}
      - task: init
      - task: dep:bootstrap
      - task: dep:install
      - task: local:cv:generate-tex

  build:site:
    desc: Build the site via Hugo
    cmds:
      - hugo

  serve:
    desc: Serve the HTML site
    cmds:
      - hugo server --environment development --buildDrafts

  s3:cv:upload:
    desc: Upload the CV PDF to AWS S3
    cmds:
      - aws s3 cp --acl public-read StephaneWirtel.pdf s3://public-mgxio/wirtel.be/StephaneWirtel.pdf

  github:cv:build:
    desc: Trigger CV build and deployment on GitHub Actions
    cmds:
      - gh workflow run build-pdf.yml

  new:post:
    desc: Create a new post
    vars:
      TODAY:
        sh: date +%Y-%m-%d
    cmds:
      - hugo new content content/post/{{.TODAY}}-{{ humanize .ARGS | title }}

  migrate:obsidian:
    desc: Convert Obsidian note to Hugo post
    cmds:
      - "{{ .LOCAL_PYTHON }} scripts/obsidian2hugo.py '{{ .OBSIDIAN_VAULT_PATH }}'"

  stats:content:
    desc: Show content statistics
    cmds:
      - echo "Total posts:" && find content/post -name "*.md" | wc -l
      - echo "Total talks:" && find content/talk -name "*.md" | wc -l
      - echo "Total projects:" && find content/project -name "*.md" | wc -l

  stats:words:
    desc: Count words in posts
    cmds:
      - hugo list all | awk '{sum+=$4} END {print "Total words:", sum}'

  renovate:check:
    desc: Check for GitHub Actions updates with Renovate
    cmds:
      - RENOVATE_TOKEN=$(gh auth token) npx renovate --platform=github --dry-run=full --enabled-managers=github-actions matrixise/www.wirtel.be

  renovate:check:all:
    desc: Check all dependencies (GitHub Actions + Python)
    cmds:
      - RENOVATE_TOKEN=$(gh auth token) npx renovate --platform=github --dry-run=full matrixise/www.wirtel.be

  renovate:check:verbose:
    desc: Check for updates with verbose output
    cmds:
      - LOG_LEVEL=debug RENOVATE_TOKEN=$(gh auth token) npx renovate --platform=github --dry-run=full --enabled-managers=github-actions matrixise/www.wirtel.be
