---
site_url: https://wirtel.be
backend:
  name: github
  repo: matrixise/www.wirtel.be
media_folder: static/img
public_folder: /img
collections:
  - name: post
    label: Post
    folder: 'content/post'
    create: true
    editor:
      preview: true
    fields:
      - label: Title
        name: title
        widget: string
      - label: Description
        name: decription
        widget: string
      - label: Date
        name: date
        widget: datetime
      - label: Body
        name: body
        widget: markdown
      - label: Tags
        name: tags
        widget: list
        allow_add: true
        default: ["python"]
  - name: project
    label: Project
    folder: 'content/project'
    create: true
    editor:
      preview: true
    fields:
      - label: Title
        name: title
        widget: string
      - label: Date
        name: date
        widget: date
      - label: Body
        name: body
        widget: markdown
  - name: talk
    label: Talk
    folder: 'content/talk'
    create: true
    editor:
      preview: true
    fields:
      - label: Title
        name: title
        widget: string
      - label: Description
        name: description
        widget: string
      - label: Date
        name: date
        widget: date
      - label: Body
        name: body
        widget: markdown
